### ISSUE TITLE
Error when using CLIP ViT-L/14 instead of ViT-B/16 

### ISSUE THREAD

**Issue by goncayilmaz** [muzairkhattak/multimodal-prompt-learning#46]
Hello,

I am trying to use MaPLe for another dataset and I wanted to try using CLIP ViT-L/14 instead of the default ViT-B/16. Although I train the model from scratch, I am getting this error when I want to run the training script:

Turning off gradients in both the image and the text encoder
Parameters to be updated: {'prompt_learner.compound_prompt_projections.0.bias', 'prompt_learner.proj.bias', 'prompt_learner.compound_prompt_projections.1.bias', 'prompt_learner.proj.weight', 'prompt_learner.compound_prompt_projections.0.weight', 'prompt_learner.compound_prompt_projections.1.weight', 'prompt_learner.compound_prompts_text.0', 'prompt_learner.ctx', 'prompt_learner.compound_prompts_text.1'}
Loading evaluator: Classification
No checkpoint found, train from scratch
Initialize tensorboard (log_dir=output/scannetpp/MaPLe/vit_b16_c2_ep5_batch4_2ctx_cross_datasets_16shots/seed12/tensorboard)
 ** On entry to SGEMM  parameter number 10 had an illegal value
Traceback (most recent call last):
  File "multimodal-prompt-learning/train.py", line 236, in <module>
    main(args)
  File "/multimodal-prompt-learning/train.py", line 179, in main
    trainer.train()
  File "/Dassl.pytorch/dassl/engine/trainer.py", line 386, in train
    super().train(self.start_epoch, self.max_epoch)
  File "/Dassl.pytorch/dassl/engine/trainer.py", line 250, in train
    self.run_epoch()
  File "/Dassl.pytorch/dassl/engine/trainer.py", line 596, in run_epoch
    loss_summary = self.forward_backward(batch)
  File "/multimodal-prompt-learning/trainers/maple.py", line 282, in forward_backward
    scaler.update()
  File "//maple/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/multimodal-prompt-learning/trainers/maple.py", line 193, in forward
    prompts, shared_ctx, deep_compound_prompts_text, deep_compound_prompts_vision = self.prompt_learner()
  File "/maple/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/multimodal-prompt-learning/trainers/maple.py", line 173, in forward
    visual_deep_prompts.append(layer(self.compound_prompts_text[index]))
  File "/maple/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/maple/lib64/python3.9/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/maple/lib64/python3.9/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

Do you know why this could be happening?

**Comment by muzairkhattak** [comment]
Hi @goncayilmaz,

Thank you for showing interest in MaPLe! 

We have not observed such an error before. Can you try and check the following:
1) Are you using a single GPU to train the model? Currently, our code only supports single GPU training. 
2) With L/14 model, I think the number of transformer layers and the hidden dimension size will change as well. You can make sure that these changes are consistent with the dimensions of the learnable prompts. 
3) Also the dimensions of the coupling function (linear layer) should be correct to handle the increased hidden dimension size of prompt tokens.

Let us know if that helps. Kind regards!

**Comment by goncayilmaz** [comment]
Hello,

thank you so much for the in-depth answer. It was indeed caused by the dimension size mismatch.

**Comment by 1028Bjt** [comment]
> Reference in new issue
Excuse me for bothering you. I would like to know how you solved this problem. Looking forward to your answer. Best wishes
