### ISSUE TITLE
After modifying MODEL:BACKBONE:NAME to “RN50” in the file vit_b16_c2_ep5_batch4_2ctx.yaml, I encountered an issue during training.

### ISSUE THREAD

**Issue by 904763189cy** [muzairkhattak/multimodal-prompt-learning#49]
An error occurred with this line of the code:  image_features = self.image_encoder(image.type(self.dtype), shared_ctx, deep_compound_prompts_vision)

Why did this error occur, and how can I resolve it?

Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main(args)
  File "train.py", line 219, in main
    trainer.train()
  File "/home/visionx/CIY/Projects/multimodal-prompt-learning/Dassl.pytorch/dassl/engine/trainer.py", line 430, in train
    super().train(self.start_epoch, self.max_epoch)
  File "/home/visionx/CIY/Projects/multimodal-prompt-learning/Dassl.pytorch/dassl/engine/trainer.py", line 266, in train
    self.run_epoch()
  File "/home/visionx/CIY/Projects/multimodal-prompt-learning/Dassl.pytorch/dassl/engine/trainer.py", line 694, in run_epoch
    loss_summary = self.forward_backward(batch)
  File "/home/visionx/CIY/Projects/multimodal-prompt-learning/trainers/maple.py", line 394, in forward_backward
    loss = model(image, label)
  File "/home/visionx/anaconda3/envs/maple/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/visionx/CIY/Projects/multimodal-prompt-learning/trainers/maple.py", line 232, in forward
    image_features = self.image_encoder(image.type(self.dtype), shared_ctx, deep_compound_prompts_vision)
  File "/home/visionx/anaconda3/envs/maple/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 4 were given

**Comment by muzairkhattak** [comment]
Hi @904763189cy,

Thank you for showing interest in MaPLe! 

Regarding your question, kindly note that our repository only supports Vision Transformers-based CLIP models for MaPLe method. 

MaPLe cannot be directly integrated into ResNet-based architectures as there is no token sequence present in the ResNet visual backbone. 

I hope that is helpful. 

Kind regards!
Uzair

**Comment by muzairkhattak** [comment]
Hi @904763189cy, I hope your issue is resolved now. 

Feel free to reopen the issue if you have any questions. 

Thank you and kind regards!
